name: db_flutter
description: "A Database service package"
version: 1.0.0
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it:
  injectable:
  path: ^1.9.0
  sqflite:
  sqflite_common:


dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator:
  mocktail: ^1.0.4
  sqflite_common_ffi:

flutter:
